### ISSUE TITLE
Add method extensions for string.Format.

### ISSUE THREAD

**Issue by Kuinox** [Invenietis/CK-ActivityMonitor#3]
Hello,
Some logger have the behavior of string.Format directly in the log method.
It require a lot of manual fixes to port these logger to the ActivityMonitor due to this, It would be nice to have extensions methods with string.Format to reduce the work to do.

**Comment by olivier-spinelli** [comment]
No way! :)
In addition to polluting the API with a lot of overloads (this was hoaw it worked before string interpolation has been made available) AND not handling the implicit techincal debt, this would prevent one of the next step of the ActivityMonitor development: using the interpolated string to work a little bit like serilog....
